# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armgui_ik.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 576)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labels1 = QtWidgets.QLabel(self.centralwidget)
        self.labels1.setGeometry(QtCore.QRect(620, 90, 91, 16))
        self.labels1.setObjectName("labels1")
        self.labels2 = QtWidgets.QLabel(self.centralwidget)
        self.labels2.setGeometry(QtCore.QRect(620, 120, 91, 16))
        self.labels2.setObjectName("labels2")
        self.labels3 = QtWidgets.QLabel(self.centralwidget)
        self.labels3.setGeometry(QtCore.QRect(620, 150, 91, 16))
        self.labels3.setObjectName("labels3")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setEnabled(True)
        self.MplWidget.setGeometry(QtCore.QRect(20, 30, 581, 491))
        self.MplWidget.setMouseTracking(True)
        self.MplWidget.setTabletTracking(True)
        self.MplWidget.setObjectName("MplWidget")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(720, 200, 221, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.labels2_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels2_ik.setGeometry(QtCore.QRect(620, 320, 91, 16))
        self.labels2_ik.setObjectName("labels2_ik")
        self.labels1_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels1_ik.setGeometry(QtCore.QRect(620, 290, 91, 16))
        self.labels1_ik.setObjectName("labels1_ik")
        self.labels3_ik = QtWidgets.QLabel(self.centralwidget)
        self.labels3_ik.setGeometry(QtCore.QRect(620, 350, 91, 16))
        self.labels3_ik.setObjectName("labels3_ik")
        self.label_ik = QtWidgets.QLabel(self.centralwidget)
        self.label_ik.setGeometry(QtCore.QRect(620, 260, 151, 16))
        self.label_ik.setObjectName("label_ik")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 450, 391, 61))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.doubleSpinBox1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox1.setGeometry(QtCore.QRect(700, 90, 62, 22))
        self.doubleSpinBox1.setAccelerated(True)
        self.doubleSpinBox1.setMinimum(0.0)
        self.doubleSpinBox1.setMaximum(180.0)
        self.doubleSpinBox1.setObjectName("doubleSpinBox1")
        self.doubleSpinBox2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox2.setGeometry(QtCore.QRect(700, 120, 62, 22))
        self.doubleSpinBox2.setAccelerated(True)
        self.doubleSpinBox2.setMinimum(-90.0)
        self.doubleSpinBox2.setMaximum(90.0)
        self.doubleSpinBox2.setObjectName("doubleSpinBox2")
        self.doubleSpinBox3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox3.setGeometry(QtCore.QRect(700, 150, 62, 22))
        self.doubleSpinBox3.setAccelerated(True)
        self.doubleSpinBox3.setMinimum(-90.0)
        self.doubleSpinBox3.setMaximum(90.0)
        self.doubleSpinBox3.setObjectName("doubleSpinBox3")
        self.label_fk = QtWidgets.QLabel(self.centralwidget)
        self.label_fk.setGeometry(QtCore.QRect(620, 60, 161, 16))
        self.label_fk.setObjectName("label_fk")
        self.doubleSpinBox_ik1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik1.setGeometry(QtCore.QRect(700, 290, 62, 22))
        self.doubleSpinBox_ik1.setAccelerated(True)
        self.doubleSpinBox_ik1.setMinimum(-99.0)
        self.doubleSpinBox_ik1.setObjectName("doubleSpinBox_ik1")
        self.doubleSpinBox_ik2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik2.setGeometry(QtCore.QRect(700, 320, 62, 22))
        self.doubleSpinBox_ik2.setAccelerated(True)
        self.doubleSpinBox_ik2.setObjectName("doubleSpinBox_ik2")
        self.doubleSpinBox_ik3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_ik3.setGeometry(QtCore.QRect(700, 350, 62, 22))
        self.doubleSpinBox_ik3.setAccelerated(True)
        self.doubleSpinBox_ik3.setObjectName("doubleSpinBox_ik3")
        self.pushButton_runik = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runik.setGeometry(QtCore.QRect(780, 290, 161, 81))
        self.pushButton_runik.setObjectName("pushButton_runik")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labels1.setText(_translate("MainWindow", "Joint 1 Angle:"))
        self.labels2.setText(_translate("MainWindow", "Joint 2 angle:"))
        self.labels3.setText(_translate("MainWindow", "Joint 3 angle:"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.labels2_ik.setText(_translate("MainWindow", "Y Axes: "))
        self.labels1_ik.setText(_translate("MainWindow", "X axes: "))
        self.labels3_ik.setText(_translate("MainWindow", "Z axes: "))
        self.label_ik.setText(_translate("MainWindow", "PINJ Inverse Kinematics"))
        self.label.setText(_translate("MainWindow", "Indra Agustian,  Electrical Engineering Dept., University of Bengkulu"))
        self.label_fk.setText(_translate("MainWindow", "DH-Forward Kinematics"))
        self.pushButton_runik.setText(_translate("MainWindow", "Run IK"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

